name: tryfigma
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  
  google_generative_ai: ^0.4.7
  speech_to_text: ^7.0.0 
   # Use this more stable version
  flutter_tts: ^4.2.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^8.0.6 # Or the latest version
  
  flutter_svg: ^2.0.9
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^7.0.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_database: ^11.3.5
  firebase_storage: ^12.4.5
  cloud_firestore: ^5.6.7
  intl: ^0.20.2
  mobile_scanner: ^7.0.0
  geolocator: ^14.0.0
  http: ^1.4.0
  google_maps_flutter: ^2.12.2
  url_launcher: ^6.3.1
  google_fonts: ^6.1.0
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^19.2.1 # Use this older stable version
  

dev_dependencies:
  
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1 # Or the latest version

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/sign_up_icon/
    - assets/icons/profile/
flutter_launcher_icons:
  android: "launcher_icon" # can be true, false, or "launcher_icon"
  ios: true
  image_path: "assets/images/logu0.png" # Path to your master logo image
  min_sdk_android: 21 # Optional
  remove_alpha_ios: true
  # You can also specify adaptive icon settings for Android:
  # adaptive_icon_background: "#FFFFFF"
  # adaptive_icon_foreground: "assets/images/new_app_logo_foreground.png"
  

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
